main:
    sampleData: "sampleData.csv" # "config/sampleData.csv is the sample file that can be used for testing the pipeline setup"
    logPath: "logs/"
    interimPath: "interim/"
    resultPath: "results/"
    prefix: "veryImportantSamples" # this prefix will be used to name the final report file

tools:
    checkm2:
        dbpath: /path/to/CheckM2_database/ # path to the db, downloaded with 'wget https://zenodo.org/records/14897628/files/checkm2_database.tar.gz'
    gtdbtk:
        dbpath: /path/to/GTDB-Tk_release226/  # path to the db, downloaded with 'wget https://data.gtdb.ecogenomic.org/releases/release226/226.0/auxillary_files/gtdbtk_package/full_package/gtdbtk_r226_data.tar.gz'
    infernal:
        dbpath: infernal/ # path where the Rfam 16S rRNA db will be created